---
- name: test create server
  hosts: localhost
  gather_facts: False
  tasks:
    - name: create server
      clc_server:
        name: btest
        template: ubuntu-14-64
        location: 'CA1'
        group: 'Default Group'
        count: 2
      register: clc-svr
    - debug: var=clc_svr
